server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
    ##设为false，关闭自我保护主要
    evictionIntervalTimerInMs: 4000
    ##清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    ##租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 2
    ##租期到期时间（默认90秒）
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/